MD013:
  line_length: 180
  code_blocks: false
  tables: false
MD033:
  allowed_elements:
    - img
    - a
    - table
    - thead
    - tbody
    - tr
    - th
    - td
    - li
    - ul
    - ol
    - kbd
MD041: false
MD046:
  style: fenced
MD029:
  style: one
MD025:
  front_matter_title: ""
