#!/usr/bin/env python3
"""Render the two tracking epics from the register."""
import json
from collections import defaultdict
from pathlib import Path

from notitiae.corpus import REPO_ROOT

REGISTER = REPO_ROOT / "docs/decrees/notitiae-register.json"
OUT = Path(__file__).with_name("out")
LEVEL_ORDER = {"general": 0, "wider_region": 1, "national": 2, "diocesan": 3, "religious": 4, "other": 5}


def heading(e: dict) -> str:
    t = e["target"]
    return {
        "general": "General Roman Calendar",
        "wider_region": f"Wider region: {t.get('wider_region')}",
        "national": t.get("nation") or "Unknown nation",
        "diocesan": f"{t.get('nation') or '??'} / {t.get('diocese') or t.get('diocese_id')}",
        "religious": f"Religious: {t.get('institute')}",
    }.get(t["level"], "Other")


def line(e: dict) -> str:
    box = "x" if e["api"]["status"] == "applied" else " "
    s = e["source"]
    applied = f" — applied in {e['api']['applied_in']}" if e["api"]["applied_in"] else ""
    review = " ⚠ needs review" if e["needs_review"] else ""
    return (f"- [{box}] `{e['id']}` {e['date'] or '????-??-??'} · {e['protocol'] or 'no protocol'} · {e['summary_en']} "
            f"([Notitiae {s['year']} p. {s['printed_pages'][0] or '?'}]({s['url']}#page={s['pdf_pages'][0]})){applied}{review}")


def body(entries: list[dict], title: str) -> str:
    groups: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        groups[heading(e)].append(e)
    ordered = sorted(groups.items(), key=lambda kv: (LEVEL_ORDER[kv[1][0]["target"]["level"]], kv[0]))
    parts = [f"# {title}", "", "Generated by `scripts/notitiae/issues.py` from `docs/decrees/notitiae-register.json`; "
             "do not edit checkboxes by hand — update the register and re-render.", ""]
    for name, items in ordered:
        parts += [f"## {name}", ""] + [line(e) for e in items] + [""]
    return "\n".join(parts)


def render(entries: list[dict]) -> tuple[str, str]:
    impl = [e for e in entries if e["api"]["calendar_implemented"]]
    rest = [e for e in entries if not e["api"]["calendar_implemented"]]
    return (body(impl, "Notitiae survey — decrees for implemented calendars"),
            body(rest, "Notitiae survey — decrees for calendars not yet implemented"))


def main() -> None:
    impl, rest = render(json.loads(REGISTER.read_text()))
    OUT.mkdir(exist_ok=True)
    (OUT / "epic-implemented.md").write_text(impl)
    (OUT / "epic-not-implemented.md").write_text(rest)
    print(f"wrote {OUT}/epic-implemented.md and epic-not-implemented.md")


if __name__ == "__main__":
    main()
